sudo: required

language: python

services:
  - docker

script:
  - docker build -t pyopcode .
  - mkdir dist
  - docker run --rm pyopcode cat /io/dist/repaired/pyopcode-0.3.5-cp36-cp36m-manylinux1_x86_64.whl > dist/pyopcode-0.3.5-cp36-cp36m-manylinux1_x86_64.whl
