environment:
  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: C:\Miniconda-x64
      CONDA_PY: 27
      CONDA_NPY: 110

    - PYTHON: C:\Miniconda35-x64
      CONDA_PY: 35
      CONDA_NPY: 110

platform:
  - x64

install:
  # we have to prepend the conda python to the path
  # and that would make it too long, so we redefine the whole thing here
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;
  - set PATH=%PATH%;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Mercurial;
  - set PATH=%PATH%;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;

  # make sure conda is up to date and configured
  - conda update conda --yes --quiet
  - conda config --set show_channel_urls True --set always_yes True

  # Install the necessary packages
  - conda install conda-build jinja2 anaconda-client --quiet
  # Show us the conda configuration we have right now
  - conda info -a
  # If this needs any private packages, we'll have to be more creative
  - conda env create --quiet

# See https://github.com/scikit-learn/scikit-learn/blob/master/appveyor.yml for inspiration
build_script:
  # There are so many dependencies for the invoke commands that it's easier to use the environment
  - activate pyopcode
  # build conda package; no upload
  - invoke build
