name: pyopcode
channels:
  - conda-forge  # for boost
  - clinicalgraphics
dependencies:
  - python =3.5*
  - numpy >=1.10
  # cppdev
  - cmake
  - boost
  # pydev
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - requests =2.9*
  - setuptools
  # tests
  - pytest =2.8*