name: pyopcode
channels:
  - anaconda
  - conda-forge  # for boost
  - clinicalgraphics
dependencies:
  - python =2.7*
  - numpy >=1.10
  # cppdev
  - cmake
  - boost =1.6*
  # pydev
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - requests =2.9*
  - setuptools
  # tests
  - pytest =2.8*
  - mock =1.3*
  - pytest-mock =0.10*
  - pytest-cov =2.2.1
  - pytest-xdist =1.14
