about:
  home: hhttps://github.com/ClinicalGraphics/pyopcode
  license: LGPL
  summary: OPCODE collision detection wrapped library with numpy bindings
build:
  features:
  - vc9                [win and py27]
  - vc10               [win and py34]
  - vc14               [win and py35]
  number: 1
package:
  name: pyopcode
  version: 0.1.9
requirements:
  build:
  - python
  - numpy 1.10*
  - gcc 4.8.2 [linux]
  - cmake 3.5*
  - boost 1.6*
  - pyyaml 3.11*
  - setuptools
  run:
  - python
  - numpy 1.10*
  - boost 1.6*
  - libgcc [linux]
  - future
source:
  path: ..
test:
  imports:
  - pyopcode
  commands:
  - py.test --pyargs pyopcode
  requires:
  - pytest 2.9*
