about:
  home: hhttps://github.com/ClinicalGraphics/pyopcode
  license: LGPL
  summary: OPCODE collision detection wrapped library with numpy bindings
package:
  name: pyopcode
  version: 0.1.dev0
source:
  path: ..
  #git_url: https://github.com/ClinicalGraphics/pyopcode.git

build:
  number: 0
  preserve_egg_dir: True
  features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

requirements:
  build:
    - gcc [linux and (py27 or py34 or py35)]
    - cmake
    - boost
    - python
    - numpy 1.10*
    - pyyaml 3.11*
    - setuptools

  run:
    - python
    - numpy 1.10*
    - future

test:
  imports:
    - pyopcode
#  commands:
#    - py.test
#  requires:
#    - pytest 2.8*
#    - mock 1.3*
#    - pytest-mock 0.10*
#    - pytest-cov 2.2.1
