about:
  home: hhttps://github.com/ClinicalGraphics/pyopcode
  license: LGPL
  summary: OPCODE collision detection wrapped library with numpy bindings
package:
  name: pyopcode
  version: 0.1.dev0
source:
  path: ..
  #git_url: https://github.com/ClinicalGraphics/pyopcode.git

build:
  number: 0
  preserve_egg_dir: True
  features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

requirements:
  build:
    - gcc 4.8.2 [linux and (py27 or py34 or py35)]
    - cmake 3.5*
    - boost
    - python
    - numpy 1.10*
    - pyyaml 3.11*
    - setuptools

  run:
    - python
    - libgcc # [linux and (py27 or py34 or py35)]
    - numpy 1.10*
    - future

test:
  imports:
    - pyopcode